version: '3'
services:
  ttbot:
    image: alsstundenplanbot/bot
    restart: always
    volumes:
      - ./config/:/timetablebot/config
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - database_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abcdef1234
      - MYSQL_USER=timetablebot
      - MYSQL_PASSWORD=abcdef1234
      - MYSQL_DATABASE=timetablebot
volumes:
  database_data: {}