# https://docs.docker.com/compose/compose-file/
version: '3'
services:
  ttbot:
    # https://hub.docker.com/r/alsstundenplanbot/bot
    # Use 'build: .' instead of 'image:...' if you want to test your local code changes
    image: timetablebot/bot
    restart: always
    volumes:
      - ./config/:/timetablebot/config
    depends_on:
      - mariadb
  mariadb:
    # https://hub.docker.com/r/yobasystems/alpine-mariadb/
    image: yobasystems/alpine-mariadb
    restart: always
    volumes:
      - database_data:/var/lib/mysql
    environment:
      # WARNING: Change the passwords, if you open the port "3306"
      # If you change the MYSQL_USER or MYSQL_PASSWORD or MYSQL_DATABASE,
      # you also have to update the configuration file
      - MYSQL_ROOT_PASSWORD=abcdef1234
      - MYSQL_USER=timetablebot
      - MYSQL_PASSWORD=abcdef1234
      - MYSQL_DATABASE=timetablebot
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
volumes:
  database_data: {}